### ISSUE TITLE
there is a api that can get the hdfs disk usage summary?

### ISSUE THREAD

**Issue by anan-lee** [cloudera/cm_api#48]
anyone can help me ?

**Comment by roaringoasis** [comment]
I believe you should be able to extract that sort of information from the cm_api [time-series](https://cloudera.github.io/cm_api/apidocs/v12/path__timeseries.html) resource

**Comment by andyao1** [comment]
Unfortunately, the API to get the HDFS disk usage summary are not exposed in the public API yet.

**Comment by anan-lee** [comment]
got
